---
# tasks file for roles/createuser


- name: Include config.yml
  include_vars:
          file: ../files/config.yml

- name: Create User
  user:
          name: choong
          comment: Choongqihan Choong
          shell: /bin/bash
